### ISSUE TITLE
string.format with commentstring fails for languages with % as comment

### ISSUE THREAD

**Issue by isaksamsten** [milanglacier/minuet-ai.nvim#8]
Hi!

I just tried your plugin and for languages (in my case it was LaTeX) with `%` as comment, the use of `string.format` fails.

I came up with this fix:

```lua
    local commentstring = vim.bo.commentstring:gsub('%%([^%w])', '%%%%%1'):gsub('%%$', '%%%%')
    return string.format(commentstring, string.format('language: %s', vim.bo.ft))
```

- `gsub("%%([^%w])", "%%%%%1")` matches a `%` that is followed by any non-alphanumeric character (meaning it will catch `%` followed by spaces, punctuation, etc.), and replaces it with an escaped version (`%%`).
- `gsub("%%$", "%%%%")` handles the (unlikely) edge case where the `%` is at the end of the string. The pattern `%%$` matches a `%` at the end of the string, and the replacement `%%%%` adds the escaping.

**Comment by milanglacier** [comment]
thanks for the catching the bugs.

I just feel strange that vim didn’t escape the `%` for us… This should definitely be an upstream bug? Anyway I will make the fix. Thank you again.

**Comment by milanglacier** [comment]
I decide to make it simpler, by using the pattern:

```
vim.bo.commentstring:gsub('^%% ', '%%%% '):gsub('%%$', '%%%%')
```

Because the format string support many different options, like `%.2f`, `%-10s`, etc. If you want to write a precise function to escape, that would be too complicated. Since we are just escape `%` in the comment string. I highly doubt that in such case `^%% ` would be sufficient as I highly doubt that there would be any other possible pattern.
